name: Update Subscription Configson:schedule:- cron: '*/30 * * * *'workflow_dispatch:jobs:update-configs:runs-on: ubuntu-latestpermissions:contents: writesteps:- name: Checkout repositoryuses: actions/checkout@v4  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
  - name: Run update script
    run: python update_configs.py

  - name: Commit and push changes
    run: |
      git config --global user.name 'github-actions[bot]'
      git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      git add Index.html
      if ! git diff --staged --quiet; then
        git commit -m "Automated: Update configs"
        git push
      else
        echo "No changes to commit."
      fi
